### PR TITLE
Schema and ERD

### PR DESCRIPTION
**Pull request by navaneeth-kalvium**
https://www.loom.com/share/61983b32a65244818e53f51df561fd4c?sid=30d68adc-c3e8-4a97-944f-ea2658ac301c

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
The design is not properly implemented.
Students - should have only students details and not Job_Id, company_id attribute, and it should have college_id foreign key connection with college entity.

Company - should not have vacancies, only Job should have vacancies

Placement - should have student_id, job_id foreign keys connection.

Update the design in meaningful way.

**Comment by navaneeth-kalvium** [comment]
Okay, I will update it soon. Thank you for the feedback.

**Comment by PRASANNAPATHI** [comment]
Hi @navaneeth-kalvium, please book a slot in my calendar. Let's have a viva session.

**Comment by navaneeth-kalvium** [comment]
PMS_ERD drawio


PMS_Schema_Diagram

**Comment by PRASANNAPATHI** [comment]
Approved in viva,

Please, merge it now for Schema & ERD.

**Pull request merged**
